### ISSUE TITLE
Don't Repeat Yourself

### ISSUE THREAD

**Issue by DanBaDo** [siemeris/ExcuseGenerator#3]
Estas líneas son exactamente iguales excepto por el array que se menciona en cada una de ellas. No sólo son iguales sino que cumplen la misma función (no parecida, la misma): Obtener una posición al azar en un array.

Cuando nos demos cuenta de estas situaciones debemos mover ese fragmento de código a una función que podamos reutilizar. En lineas generales, la parte del código que cambia (para el caso, el array) constituirá los argumentos de la función, y el valor que obtenemos con ese código (el índice aleatorio) lo entregaremos desde el cuerpo de la función con el return.

```
Encabezado -> funtion randomIndexIn ( originArray ) 
Salida (return) ->  Índice aleatorio dentro de la longitud de originArray 
```

https://github.com/siemeris/ExcuseGenerator/blob/8efc75bbdfc811c502e2ec65337790b12778fe4a/src/app.js#L28-L31

**Comment by siemeris** [comment]
Muchas gracias Daniel, reorganicé el código y creé la función randomIndex, creo que ahora se entiende mejor.
